### ISSUE TITLE
Review and tidy-up notes July 2023

### ISSUE THREAD

**Issue by phockett** [phockett/Quantum-Metrology-with-Photoelectrons-Vol3#11]
Final pass for most docs, hopefully, on branch `reviewJuly2023`

- [ ] Update text. Versions to new date-stamp as revised, and update TOC to reflect.
- [ ] Check/test individual notebooks in current Docker build.
- [ ] Debug HTML and PDF builds.
- [ ] Wrap up case studies.

To do:

- Installation guide in main readme, and also at end of "Platform intro" chpt.
   - Review current Docker build.
   - Script this for local Python installs, and also for full Docker build.

**Comment by phockett** [comment]
UGH - main comment above overwritten by Firefox cached version... here's full previous text...

Final pass for most docs, hopefully, on branch reviewJuly2023, reviewJuly2023

- [ ]    Update text. Versions to new date-stamp as revised, and update TOC to reflect.
        58f3773c662e461f4c0f768f0805b99de1be2ae6 Adds frame defintion section (needs some work) and alignment section
        (stub).
        Theory:
            Swap section ordering? Or add note/figure in intro to this effect.
            Finish observables by type sections.
            Promote symmetry subsubsection to subsection (may also fix maths rendering issues in "photoionziation dynamics" parent subsection). UPDATE: did this anyway, but rendering issues also fixed with pkg versions in 15/07/23 builds.
            Clarify LF/AF coupling term - this currently mixes LF and MF definitions for latter case (now fixed in code, see also MF recon manuscript)?
            Add some notes on alignment? Currently introduced numerically later. (E.g. alignment tensor section). Should include some plots. NOTE: issues with Matplotlib plots in builds 19/07/23, seem to be related to MolPlot routine triggering errors (Arrow3D issues). BUT OK for <v3.6. pip install matplotlib==3.5.3 is working, now set in Dockerfile_qm3_local_install_from_base.
                This version OK in Jupyter directly in testing, but failing in book build 21/0723 - still some Matplotlib issue.
                Ah, looks like issue is Arrow3D class, needs patching for Matplotlib >v3.5, see stackoverflow.com/a/74122407 TODO: add to ePSproc with conditional patching depending on MPL version.
                Add 'glue' refs to page for builds.
        Numerics intro section. Updated 24/07/23, passable - content better, but quite a bit of overlap with Chpt. 2; some parts could move to PARTII?

    Check/test individual notebooks in current Docker build.
        Fix fig object return in epsproc.sphFromBLMPlot for Plotly case.
        Fix data.padPlot for basic case, already did this...? Currently issues with missing defaults due to (recent?) changes in code, see broken example here. Should now be fixed (in next build), see phockett/ePSproc#27 (comment)
        Issue in Density Mat notebook with setup script (%run '../scripts/setup_symmetry_basis_tensors.py') in 19/07/23 builds - but rest of notebook seems OK however. UPDATE: removed from script in 59edb777677b25f06f137421339d5bf4e971f366.
        Info content notebook now returning all zero BLMs... no idea why
            Test change in default phaseConventions
            Test change in default sumDims
            AH - likely due to addition of dipole filtering in calcs? Need to add per phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part2/sym-fitting-intro_220423.html#mapping-symmetrized-harmonics-to-fit-parameters. Quick test unsuccessful, will need a more careful revisit.

    Debug HTML and PDF builds.
        Density matrix chpt. no figures in PDF builds (as of 11/07/23)? May be related to QuTip issues (see #8 ), although those cells are hidden in PDF build.
        Part labelling - need to add explicitly for HTML builds, but this messes up PDF builds currently. (Which adds additional "Part" labels.). For linking to Part II in text can use {ref}Part II chpt:extracting-matrix-elements-overview``.
        Build 2023-07-22 now deployed to Github. Fixed to Sect. 3.6. NEW ISSUES with Plotly figure rendering however. Due to changes to setup script? Thought this had been undone, but maybe stuck in cached files.

    Wrap up case studies.

    General Docker builds for readers, and push to Docker hub.
        Current working version with Jupyter Stacks builds circa May 2023, issues with Jupyter Lab builds in new images (?).
        Now running tests with v2023-05-15 - but note this is Python 3.10, not Python 3.9.7 as previously!
        Now running tests with v2023-05-19 - Matplotlib issues in Alignment plotting (v3.7 vs. 3.4 previously).

    Tidy/remove/archive drafts

    Tidy scripts

    Tidy build chain and finalise Docker build files and notes.

To do:

    Installation guide in main readme, and also at end of "Platform intro" chpt. (Old version here.)
        Review current Docker build.
        Script this for local Python installs, and also for full Docker build.
        General routine for locating setup-notebook.py script? Still OK to use relative paths here? Now added a note to the Installation section on this. May want to add as an appendix?
    Numerical implementations/examples
        Add MF case either in outline or in detail, see pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_demo_multi-fit_tests_130621-MFtests_120822-tidy-retest.html and pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_backends_demo_010922.html. 24/07/23 now mentioned in passing in Sects. 2.5 and 4.1.3/4.2 (in progress).

**Comment by phockett** [comment]
AND AGAIN FFS

Final pass for most docs, hopefully, on branch reviewJuly2023, [reviewJuly2023](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3/tree/reviewJuly2023)

    Update text. Versions to new date-stamp as revised, and update TOC to reflect.
        58f3773c662e461f4c0f768f0805b99de1be2ae6 Adds frame defintion section (needs some work) and alignment section (stub).
        Theory
            Swap section ordering? Or add note/figure in intro to this effect.
            Finish observables by type sections.
            Promote symmetry subsubsection to subsection (may also fix maths rendering issues in "photoionziation dynamics" parent subsection). UPDATE: did this anyway, but rendering issues also fixed with pkg versions in 15/07/23 builds.
            [Clarify LF/AF coupling term](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/theory_tensor_formalism_201122.html#molecular-frame-projection-term-lambda) - this currently mixes LF and MF definitions for latter case (now fixed in code, see also MF recon manuscript)?
            Add some notes on alignment? Currently introduced numerically later. (E.g. [alignment tensor section](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/theory_tensor_formalism_201122.html#alignment-tensor-delta-l-m-k-q-s)). Should include some plots.
                NOTE: issues with Matplotlib plots in builds 19/07/23, seem to be related to MolPlot routine triggering errors (Arrow3D issues). BUT OK for <v3.6. pip install matplotlib==3.5.3 is working, now set in Dockerfile_qm3_local_install_from_base.
                This version OK in Jupyter directly in testing, but failing in book build 21/0723 - still some Matplotlib issue.
                Ah, looks like issue is Arrow3D class, needs patching for Matplotlib >v3.5, see [stackoverflow.com/a/74122407](https://stackoverflow.com/a/74122407) TODO: add to ePSproc with conditional patching depending on MPL version.
                Add 'glue' refs to page for builds.
        Numerics intro section. Updated 24/07/23, passable - content better, but quite a bit of overlap with Chpt. 2; some parts could move to PARTII?
        Fitting intro updating 26/07/23. NOTE: keep Matplotlib plots for now, since these render directly in both PDF and HTML. Add HV plots as optional in HTML format.

    Check/test individual notebooks in current Docker build.
        Fix fig object return in epsproc.sphFromBLMPlot for Plotly case.
        Fix data.padPlot for basic case, already did this...? Currently issues with missing defaults due to (recent?) changes in code, [see broken example here](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/theory_observables_intro_211122.html). Should now be fixed (in next build), see https://github.com/phockett/ePSproc/issues/27#issuecomment-1468435262
        Issue in Density Mat notebook with setup script (%run '../scripts/setup_symmetry_basis_tensors.py') in 19/07/23 builds - but rest of notebook seems OK however. UPDATE: removed from script in 59edb777677b25f06f137421339d5bf4e971f366.
        Info content notebook now returning all zero BLMs... no idea why
            Test change in default phaseConventions
            Test change in default sumDims
            AH - likely due to addition of dipole filtering in calcs? Need to add per [phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part2/sym-fitting-intro_220423.html#mapping-symmetrized-harmonics-to-fit-parameters](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part2/sym-fitting-intro_220423.html#mapping-symmetrized-harmonics-to-fit-parameters). Quick test unsuccessful, will need a more careful revisit.
            Now fied in 9c60eafce2c7faaa8938d32156cde9179346c265, updated setup script with full symmetry routine and tested info content and density matrix chpts.

    Debug HTML and PDF builds.
        Density matrix chpt. no figures in PDF builds (as of 11/07/23)? May be related to QuTip issues (see #8 ), although those cells are hidden in PDF build. NOTE: was previously working, and do have static renders in pdf-build dir, although multiple versions, so may just need a clean/non-cached build to fix.
            Full build (no cache/force) 26/07/23 pm didn't fix. Should debug in single page build.
        MFPAD plots (Plotly) cropping after setting height=800 in plotting routine, but NOT FIXED after setting back to 1200px and clean build. Not sure what is going on there... maybe need bigger and had something cached accidentally previously? Should debug in single page build.
        Part labelling - need to add explicitly for HTML builds, but this messes up PDF builds currently. (Which adds additional "Part" labels.). For linking to Part II in text can use {ref}Part II chpt:extracting-matrix-elements-overview``.
        Outstanding issues with data.params (lmfit object) data return in [basis sets page](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part2/sym-fitting-intro_220423.html#mapping-to-fitting-parameters-and-reduction).
            OK in HTML for raw cell output, but no glue() success so far, not sure how to return PD object? Tested a few variants (text and HTML reprs), but no joy. See notebook for more comments, also https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3/issues/6.
            AH, see also https://github.com/lmfit/lmfit-py/discussions/827. NOW added to setup script, should be OK on next build.

    Wrap up case studies.
        27/07/23 consolidating general setup script. Note this is from mid-July Docker builds (runs on Fock), and still includes phase convention fix (which may be incorrect...). See https://github.com/phockett/ePSproc/issues/26#issuecomment-1640541159

    General Docker builds for readers, and push to Docker hub.
        Current working version with Jupyter Stacks builds circa May 2023, issues with Jupyter Lab builds in new images (?).
        Now running tests with v2023-05-15 - but note this is Python 3.10, not Python 3.9.7 as previously!
        Now running tests with v2023-05-19 - Matplotlib issues in Alignment plotting (v3.7 vs. 3.4 previously).
        Build 2023-07-22 now deployed to Github. Fixed to Sect. 3.6. NEW ISSUES with Plotly figure rendering however. Due to changes to setup script? Thought this had been undone, but maybe stuck in cached files.

    Tidy/remove/archive drafts

    Tidy scripts

    Tidy build chain and finalise Docker build files and notes.

To do:

    Installation guide in main readme, and also at end of "Platform intro" chpt. ([Old version here](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/platform_intro_071122.html).)
        Review current Docker build.
        Script this for local Python installs, and also for full Docker build.
        General routine for locating setup-notebook.py script? Still OK to use relative paths here? Now added a note to the Installation section on this. May want to add as an appendix?
        General notes on pkg versions, and link to build versions doc (end of book), also to add. Should release current versions and match to Docker build at completion.

    Numerical implementations/examples
        Add MF case either in outline or in detail, see [pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_demo_multi-fit_tests_130621-MFtests_120822-tidy-retest.html](https://pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_demo_multi-fit_tests_130621-MFtests_120822-tidy-retest.html) and [pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_backends_demo_010922.html](https://pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_backends_demo_010922.html). 24/07/23 now mentioned in passing in Sects. 2.5 and 4.1.3/4.2 (in progress).

**Comment by phockett** [comment]
REFERENCE CASE 27/07/23 pm

Final pass for most docs, hopefully, on branch `reviewJuly2023`, https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3/tree/reviewJuly2023

- [ ] Update text. Versions to new date-stamp as revised, and update TOC to reflect.
	- [ ] 58f3773c662e461f4c0f768f0805b99de1be2ae6 Adds frame defintion section (needs some work) and alignment section (stub). 
	- Theory
      - [x]  Swap section ordering? Or add note/figure in intro to this effect.
      - [x]  Finish observables by type sections.
      - [x]  Promote symmetry subsubsection to subsection (may also fix maths rendering issues in "photoionziation dynamics" parent subsection).  UPDATE: did this anyway, but rendering issues also fixed with pkg versions in 15/07/23 builds.
      - [ ]   [Clarify LF/AF coupling term](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/theory_tensor_formalism_201122.html#molecular-frame-projection-term-lambda) - this currently mixes LF and MF definitions for latter case (now fixed in code, see also MF recon manuscript)?
      - [ ]  Add some notes on alignment? Currently introduced numerically later. (E.g. [alignment tensor section](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/theory_tensor_formalism_201122.html#alignment-tensor-delta-l-m-k-q-s)). Should include some plots.
         - NOTE: issues with Matplotlib plots in builds 19/07/23, seem to be related to MolPlot routine triggering errors (Arrow3D issues). BUT OK for <v3.6. pip install matplotlib==3.5.3 is working, now set in Dockerfile_qm3_local_install_from_base.
         - This version OK in Jupyter directly in testing, but failing in book build 21/0723 - still some Matplotlib issue.
         - Ah, looks like issue is Arrow3D class, needs patching for Matplotlib >v3.5, see [stackoverflow.com/a/74122407](https://stackoverflow.com/a/74122407) TODO: add to ePSproc with conditional patching depending on MPL version.
  		 - [ ] Add 'glue' refs to page for builds.
  	 - [ ] Density matrix page needs a tidy.
  	 - [ ] Info content page also still to do
   - [x] Numerics intro section. Updated 24/07/23, passable - content better, but quite a bit of overlap with Chpt. 2; some parts could move to PARTII?


- [ ] Check/test individual notebooks in current Docker build.
   - [x] Fix fig object return in `epsproc.sphFromBLMPlot` for Plotly case.
   - [x] Fix `data.padPlot` for basic case, already did this...? Currently issues with missing defaults due to (recent?) changes in code, [see broken example here](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/theory_observables_intro_211122.html). Should now be fixed (in next build), see https://github.com/phockett/ePSproc/issues/27#issuecomment-1468435262
   - [x] Issue in Density Mat notebook with setup script (%run '../scripts/setup_symmetry_basis_tensors.py') in 19/07/23 builds - but rest of notebook seems OK however. UPDATE: removed from script in 59edb777677b25f06f137421339d5bf4e971f366.
   - [x] Info content notebook now returning all zero BLMs... no idea why
      - [x] Test change in default phaseConventions
      - [x] Test change in default sumDims
      - [x] AH - likely due to addition of dipole filtering in calcs? Need to add per [phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part2/sym-fitting-intro_220423.html#mapping-symmetrized-harmonics-to-fit-parameters](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part2/sym-fitting-intro_220423.html#mapping-symmetrized-harmonics-to-fit-parameters). Quick test unsuccessful, will need a more careful revisit.
      - [x]  Now fied in 9c60eafce2c7faaa8938d32156cde9179346c265, updated setup script with full symmetry routine and tested info content and density matrix chpts.


- [ ] Debug HTML and PDF builds.
   - [ ] Density matrix chpt. no figures in PDF builds (as of 11/07/23)? May be related to QuTip issues (see #8 ), although those cells are hidden in PDF build. NOTE: was previously working, and do have static renders in pdf-build dir, although multiple versions, so may just need a clean/non-cached build to fix.
      - Full build (no cache/force) 26/07/23 pm didn't fix. Should debug in single page build.
   - [ ] MFPAD plots (Plotly) cropping after setting height=800 in plotting routine, but NOT FIXED after setting back to 1200px and clean build. Not sure what is going on there... maybe need bigger and had something cached accidentally previously? Should debug in single page build.
    - [ ] Part labelling - need to add explicitly for HTML builds, but this messes up PDF builds currently. (Which adds additional "Part" labels.).  For linking to Part II in text can use `{ref}`Part II <chpt:extracting-matrix-elements-overview>``.
    - [ ] Outstanding issues with `data.params` (lmfit object) data return in [basis sets page](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part2/sym-fitting-intro_220423.html#mapping-to-fitting-parameters-and-reduction). 
       - OK in HTML for raw cell output, but no glue() success so far, not sure how to return PD object? Tested a few variants (text and HTML reprs), but no joy. See notebook for more comments, also https://github.com/phockett/Quantum-Metrology-with-Photoelectrons-Vol3/issues/6. 
       - AH, see also https://github.com/lmfit/lmfit-py/discussions/827. NOW added to setup script, should be OK on next build.

- [ ] Wrap up case studies.
   - [ ] 27/07/23 consolidating general setup script. Note this is from mid-July Docker builds (runs on Fock), and still includes phase convention fix (which may be incorrect...). See https://github.com/phockett/ePSproc/issues/26#issuecomment-1640541159

- [ ] General Docker builds for readers, and push to Docker hub.
    - [ ] Current working version with Jupyter Stacks builds circa May 2023, issues with Jupyter Lab builds in new images (?).
    - [ ] Now running tests with v2023-05-15 - but note this is Python 3.10, not Python 3.9.7 as previously!
    - [ ] Now running tests with v2023-05-19 - Matplotlib issues in Alignment plotting (v3.7 vs. 3.4 previously).
    - [ ]  Build 2023-07-22 now deployed to Github. Fixed to Sect. 3.6. NEW ISSUES with Plotly figure rendering however. Due to changes to setup script? Thought this had been undone, but maybe stuck in cached files.

- [ ] Tidy/remove/archive drafts
- [ ] Tidy scripts
- [ ] Tidy build chain and finalise Docker build files and notes.


To do:

- Installation guide in main readme, and also at end of "Platform intro" chpt. ([Old version here](https://phockett.github.io/Quantum-Metrology-with-Photoelectrons-Vol3/part1/platform_intro_071122.html).)
   - Review current Docker build.
   - Script this for local Python installs, and also for full Docker build.
   - General routine for locating `setup-notebook.py` script? Still OK to use relative paths here? Now added a note to the `Installation` section on this. May want to add as an appendix?
   - General notes on pkg versions, and link to build versions doc (end of book), also to add. Should release current versions and match to Docker build at completion.

- Numerical implementations/examples
   - Add MF case either in outline or in detail, see [pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_demo_multi-fit_tests_130621-MFtests_120822-tidy-retest.html](https://pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_demo_multi-fit_tests_130621-MFtests_120822-tidy-retest.html) and [pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_backends_demo_010922.html](https://pemtk.readthedocs.io/en/latest/fitting/PEMtk_fitting_backends_demo_010922.html). 24/07/23 now mentioned in passing in Sects. 2.5 and 4.1.3/4.2 (in progress).
